/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CheckAccessByEmail200Response { 
    /**
     * List of emails that do not have access to site.
     */
    emailsWithoutAccess?: Array<string>;
    /**
     * List of invalid emails provided in the request.
     */
    invalidEmails?: Array<string>;
}

