/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The sort fields for child custom content. The default sort direction is ascending by id. To sort in descending order, append a `-` character before the sort field. For example, `fieldName` or `-fieldName`.
 */
export type ChildCustomContentSortOrder = 'created-date' | '-created-date' | 'id' | '-id' | 'modified-date' | '-modified-date';

export const ChildCustomContentSortOrder = {
    CreatedDate: 'created-date' as ChildCustomContentSortOrder,
    CreatedDate2: '-created-date' as ChildCustomContentSortOrder,
    Id: 'id' as ChildCustomContentSortOrder,
    Id2: '-id' as ChildCustomContentSortOrder,
    ModifiedDate: 'modified-date' as ChildCustomContentSortOrder,
    ModifiedDate2: '-modified-date' as ChildCustomContentSortOrder
};

