/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The sort fields for child pages. The default sort direction is ascending by child-position. To sort in descending order, append a `-` character before the sort field. For example, `fieldName` or `-fieldName`.
 */
export type ChildPageSortOrder = 'created-date' | '-created-date' | 'id' | '-id' | 'child-position' | '-child-position' | 'modified-date' | '-modified-date';

export const ChildPageSortOrder = {
    created_date: 'created-date' as ChildPageSortOrder,
    created_date2: '-created-date' as ChildPageSortOrder,
    id: 'id' as ChildPageSortOrder,
    id2: '-id' as ChildPageSortOrder,
    child_position: 'child-position' as ChildPageSortOrder,
    child_position2: '-child-position' as ChildPageSortOrder,
    modified_date: 'modified-date' as ChildPageSortOrder,
    modified_date2: '-modified-date' as ChildPageSortOrder
};

