/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The sort fields for hierarchical content types. The default sort direction is ascending. To sort in descending order, append a `-` character before the sort field. For example, `fieldName` or `-fieldName`.
 */
export type ContentSortOrder = 'created-date' | '-created-date' | 'id' | '-id' | 'modified-date' | '-modified-date' | 'child-position' | '-child-position' | 'title' | '-title';

export const ContentSortOrder = {
    CreatedDate: 'created-date' as ContentSortOrder,
    CreatedDate2: '-created-date' as ContentSortOrder,
    Id: 'id' as ContentSortOrder,
    Id2: '-id' as ContentSortOrder,
    ModifiedDate: 'modified-date' as ContentSortOrder,
    ModifiedDate2: '-modified-date' as ContentSortOrder,
    ChildPosition: 'child-position' as ContentSortOrder,
    ChildPosition2: '-child-position' as ContentSortOrder,
    Title: 'title' as ContentSortOrder,
    Title2: '-title' as ContentSortOrder
};

