/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The status of the content.
 */
export type ContentStatus = 'current' | 'draft' | 'archived' | 'historical' | 'trashed' | 'deleted' | 'any';

export const ContentStatus = {
    Current: 'current' as ContentStatus,
    Draft: 'draft' as ContentStatus,
    Archived: 'archived' as ContentStatus,
    Historical: 'historical' as ContentStatus,
    Trashed: 'trashed' as ContentStatus,
    Deleted: 'deleted' as ContentStatus,
    Any: 'any' as ContentStatus
};

