/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SpaceDescription } from './spaceDescription';
import { SpaceType } from './spaceType';
import { GetAttachmentById200ResponseAllOfLinks } from './getAttachmentById200ResponseAllOfLinks';
import { SpaceStatus } from './spaceStatus';
import { SpaceIcon } from './spaceIcon';


export interface CreateSpace201Response { 
    /**
     * ID of the space.
     */
    id?: string;
    /**
     * Key of the space.
     */
    key?: string;
    /**
     * Name of the space.
     */
    name?: string;
    type?: SpaceType;
    status?: SpaceStatus;
    /**
     * The account ID of the user who created this space originally.
     */
    authorId?: string;
    /**
     * Date and time when the space was created. In format \"YYYY-MM-DDTHH:mm:ss.sssZ\".
     */
    createdAt?: string;
    /**
     * ID of the space\'s homepage.
     */
    homepageId?: string;
    description?: SpaceDescription;
    icon?: SpaceIcon;
    _links?: GetAttachmentById200ResponseAllOfLinks;
}
export namespace CreateSpace201Response {
}


