/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AttachmentSingleProperties } from './attachmentSingleProperties';
import { BlogPostSingleLikes } from './blogPostSingleLikes';
import { Version } from './version';
import { AttachmentSingleOperations } from './attachmentSingleOperations';
import { AttachmentSingleLabels } from './attachmentSingleLabels';
import { BlogPostContentStatus } from './blogPostContentStatus';
import { GetAttachmentById200ResponseAllOfLinks } from './getAttachmentById200ResponseAllOfLinks';
import { BodySingle } from './bodySingle';
import { AttachmentSingleVersions } from './attachmentSingleVersions';


export interface CreateBlogPost200Response { 
    /**
     * ID of the blog post.
     */
    id?: string;
    status?: BlogPostContentStatus;
    /**
     * Title of the blog post.
     */
    title?: string;
    /**
     * ID of the space the blog post is in.
     */
    spaceId?: string;
    /**
     * The account ID of the user who created this blog post originally.
     */
    authorId?: string;
    /**
     * Date and time when the blog post was created. In format \"YYYY-MM-DDTHH:mm:ss.sssZ\".
     */
    createdAt?: string;
    version?: Version;
    body?: BodySingle;
    labels?: AttachmentSingleLabels;
    properties?: AttachmentSingleProperties;
    operations?: AttachmentSingleOperations;
    likes?: BlogPostSingleLikes;
    versions?: AttachmentSingleVersions;
    /**
     * Whether the blog post has been favorited by the current user.
     */
    isFavoritedByCurrentUser?: boolean;
    _links?: GetAttachmentById200ResponseAllOfLinks;
}
export namespace CreateBlogPost200Response {
}


