/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreatePageRequestBody } from './createPageRequestBody';


export interface CreatePageRequest { 
    /**
     * ID of the space.
     */
    spaceId: string;
    /**
     * The status of the page, published or draft.
     */
    status?: CreatePageRequest.StatusEnum;
    /**
     * Title of the page, required if page status is not draft.
     */
    title?: string;
    /**
     * The parent content ID of the page. If the `root-level` query parameter is set to false and a value is  not supplied for this parameter, then the space homepage\'s ID will be used. If the `root-level` query  parameter is set to true, then a value may not be supplied for this parameter.
     */
    parentId?: string;
    body?: CreatePageRequestBody;
    /**
     * The subtype of the page. Provide the subtype live to create a live doc or no subtype to create a page.
     */
    subtype?: CreatePageRequest.SubtypeEnum;
}
export namespace CreatePageRequest {
    export type StatusEnum = 'current' | 'draft';
    export const StatusEnum = {
        Current: 'current' as StatusEnum,
        Draft: 'draft' as StatusEnum
    };
    export type SubtypeEnum = 'live';
    export const SubtypeEnum = {
        Live: 'live' as SubtypeEnum
    };
}


