/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The formats a custom content body can be represented as. A subset of BodyRepresentation.
 */
export type CustomContentBodyRepresentationSingle = 'raw' | 'storage' | 'atlas_doc_format' | 'view' | 'export_view' | 'anonymous_export_view';

export const CustomContentBodyRepresentationSingle = {
    Raw: 'raw' as CustomContentBodyRepresentationSingle,
    Storage: 'storage' as CustomContentBodyRepresentationSingle,
    AtlasDocFormat: 'atlas_doc_format' as CustomContentBodyRepresentationSingle,
    View: 'view' as CustomContentBodyRepresentationSingle,
    ExportView: 'export_view' as CustomContentBodyRepresentationSingle,
    AnonymousExportView: 'anonymous_export_view' as CustomContentBodyRepresentationSingle
};

