/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DetailedVersion { 
    /**
     * The current version number.
     */
    number?: number;
    /**
     * The account ID of the user who created this version.
     */
    authorId?: string;
    /**
     * Message associated with the current version.
     */
    message?: string;
    /**
     * Date and time when the version was created. In format \"YYYY-MM-DDTHH:mm:ss.sssZ\".
     */
    createdAt?: string;
    /**
     * Describes if this version is a minor version. Email notifications and activity stream updates are not created for minor versions.
     */
    minorEdit?: boolean;
    /**
     * Describes if the content type is modified in this version (e.g. page to blog)
     */
    contentTypeModified?: boolean;
    /**
     * The account IDs of users that collaborated on this version.
     */
    collaborators?: Array<string>;
    /**
     * The version number of the version prior to this current content update.
     */
    prevVersion?: number;
    /**
     * The version number of the version after this current content update.
     */
    nextVersion?: number;
}

