/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetSpaceRoleMode200Response { 
    /**
     * The space role mode.
     */
    mode?: GetSpaceRoleMode200Response.ModeEnum;
}
export namespace GetSpaceRoleMode200Response {
    export type ModeEnum = 'PRE_ROLES' | 'ROLES_TRANSITION' | 'ROLES';
    export const ModeEnum = {
        PRE_ROLES: 'PRE_ROLES' as ModeEnum,
        ROLES_TRANSITION: 'ROLES_TRANSITION' as ModeEnum,
        ROLES: 'ROLES' as ModeEnum
    };
}


