/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BlogPostSingleLikes } from './blogPostSingleLikes';
import { Version } from './version';
import { AttachmentSingleOperations } from './attachmentSingleOperations';
import { InlineCommentResolutionStatus } from './inlineCommentResolutionStatus';
import { InlineCommentModelProperties } from './inlineCommentModelProperties';
import { BodySingle } from './bodySingle';
import { CommentLinks } from './commentLinks';
import { AttachmentSingleVersions } from './attachmentSingleVersions';
import { ContentStatus } from './contentStatus';


export interface InlineCommentModel { 
    /**
     * ID of the comment.
     */
    id?: string;
    status?: ContentStatus;
    /**
     * Title of the comment.
     */
    title?: string;
    /**
     * ID of the blog post containing the comment if the comment is on a blog post.
     */
    blogPostId?: string;
    /**
     * ID of the page containing the comment if the comment is on a page.
     */
    pageId?: string;
    /**
     * ID of the parent comment if the comment is a reply.
     */
    parentCommentId?: string;
    version?: Version;
    body?: BodySingle;
    /**
     * Atlassian Account ID of last person who modified the resolve state of the comment. Null until comment is resolved or reopened.
     */
    resolutionLastModifierId?: string;
    /**
     * Timestamp of the last modification to the comment\'s resolution status. Null until comment is resolved or reopened.
     */
    resolutionLastModifiedAt?: string;
    resolutionStatus?: InlineCommentResolutionStatus;
    properties?: InlineCommentModelProperties;
    operations?: AttachmentSingleOperations;
    likes?: BlogPostSingleLikes;
    versions?: AttachmentSingleVersions;
    _links?: CommentLinks;
}
export namespace InlineCommentModel {
}


