/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PageBodyWrite { 
    /**
     * Type of content representation used for the value field.
     */
    representation?: PageBodyWrite.RepresentationEnum;
    /**
     * Body of the page, in the format found in the representation field.
     */
    value?: string;
}
export namespace PageBodyWrite {
    export type RepresentationEnum = 'storage' | 'atlas_doc_format' | 'wiki';
    export const RepresentationEnum = {
        Storage: 'storage' as RepresentationEnum,
        AtlasDocFormat: 'atlas_doc_format' as RepresentationEnum,
        Wiki: 'wiki' as RepresentationEnum
    };
}


