/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The primary formats a body can be represented as. A subset of BodyRepresentation. These formats are the only allowed formats in certain use cases.
 */
export type PrimaryBodyRepresentation = 'storage' | 'atlas_doc_format';

export const PrimaryBodyRepresentation = {
    Storage: 'storage' as PrimaryBodyRepresentation,
    AtlasDocFormat: 'atlas_doc_format' as PrimaryBodyRepresentation
};

