/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The icon of the space
 */
export interface SpaceIcon { 
    /**
     * The path (relative to base URL) at which the space\'s icon can be retrieved. The format should be like `/wiki/download/...` or `/wiki/aa-avatar/...`
     */
    path?: string;
    /**
     * The path (relative to base URL) that can be used to retrieve a link to download the space icon. 3LO apps should use this link instead of the value provided in the `path` property to retrieve the icon.  Currently this field is only returned for `global` spaces and not `personal` spaces. 
     */
    apiDownloadLink?: string;
}

