/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateCustomContentRequestBody } from './createCustomContentRequestBody';
import { UpdateCustomContentRequestVersion } from './updateCustomContentRequestVersion';


export interface UpdateCustomContentRequest { 
    /**
     * Id of custom content.
     */
    id: string;
    /**
     * Type of custom content.
     */
    type: string;
    /**
     * The status of the custom content.
     */
    status: UpdateCustomContentRequest.StatusEnum;
    /**
     * ID of the containing space (must be the same as the spaceId of the space the custom content was created in).
     */
    spaceId?: string;
    /**
     * ID of the containing page.
     */
    pageId?: string;
    /**
     * ID of the containing Blog Post.
     */
    blogPostId?: string;
    /**
     * ID of the containing custom content.
     */
    customContentId?: string;
    /**
     * Title of the custom content.
     */
    title: string;
    body: CreateCustomContentRequestBody;
    version: UpdateCustomContentRequestVersion;
}
export namespace UpdateCustomContentRequest {
    export type StatusEnum = 'current';
    export const StatusEnum = {
        Current: 'current' as StatusEnum
    };
}


