/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateTaskRequest { 
    /**
     * ID of the task.
     */
    id?: string;
    /**
     * Local ID of the task. This ID is local to the corresponding page or blog post.
     */
    localId?: string;
    /**
     * ID of the space the task is in.
     */
    spaceId?: string;
    /**
     * ID of the page the task is in.
     */
    pageId?: string;
    /**
     * ID of the blog post the task is in.
     */
    blogPostId?: string;
    /**
     * Status of the task.
     */
    status: UpdateTaskRequest.StatusEnum;
    /**
     * Account ID of the user who created this task.
     */
    createdBy?: string;
    /**
     * Account ID of the user to whom this task is assigned.
     */
    assignedTo?: string;
    /**
     * Account ID of the user who completed this task.
     */
    completedBy?: string;
    /**
     * Date and time when the task was created. In format \"YYYY-MM-DDTHH:mm:ss.sssZ\".
     */
    createdAt?: string;
    /**
     * Date and time when the task was updated. In format \"YYYY-MM-DDTHH:mm:ss.sssZ\".
     */
    updatedAt?: string;
    /**
     * Date and time when the task is due. In format \"YYYY-MM-DDTHH:mm:ss.sssZ\".
     */
    dueAt?: string;
    /**
     * Date and time when the task was completed. In format \"YYYY-MM-DDTHH:mm:ss.sssZ\".
     */
    completedAt?: string;
}
export namespace UpdateTaskRequest {
    export type StatusEnum = 'complete' | 'incomplete';
    export const StatusEnum = {
        Complete: 'complete' as StatusEnum,
        Incomplete: 'incomplete' as StatusEnum
    };
}


