/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WhiteboardLinks } from './whiteboardLinks';
import { Version } from './version';
import { ParentContentType } from './parentContentType';
import { ContentStatus } from './contentStatus';


export interface WhiteboardSingle { 
    /**
     * ID of the whiteboard.
     */
    id?: string;
    /**
     * The content type of the object.
     */
    type?: string;
    status?: ContentStatus;
    /**
     * Title of the whiteboard.
     */
    title?: string;
    /**
     * ID of the parent content, or null if there is no parent content.
     */
    parentId?: string;
    parentType?: ParentContentType;
    /**
     * Position of the whiteboard within the given parent page tree.
     */
    position?: number | null;
    /**
     * The account ID of the user who created this whiteboard originally.
     */
    authorId?: string;
    /**
     * The account ID of the user who owns this whiteboard.
     */
    ownerId?: string;
    /**
     * Date and time when the whiteboard was created. In format \"YYYY-MM-DDTHH:mm:ss.sssZ\".
     */
    createdAt?: string;
    version?: Version;
    _links?: WhiteboardLinks;
}
export namespace WhiteboardSingle {
}


