export * from './adminKey.service';
import { AdminKeyService } from './adminKey.service';
export * from './ancestors.service';
import { AncestorsService } from './ancestors.service';
export * from './attachment.service';
import { AttachmentService } from './attachment.service';
export * from './blogPost.service';
import { BlogPostService } from './blogPost.service';
export * from './children.service';
import { ChildrenService } from './children.service';
export * from './classificationLevel.service';
import { ClassificationLevelService } from './classificationLevel.service';
export * from './comment.service';
import { CommentService } from './comment.service';
export * from './content.service';
import { ContentService } from './content.service';
export * from './contentProperties.service';
import { ContentPropertiesService } from './contentProperties.service';
export * from './customContent.service';
import { CustomContentService } from './customContent.service';
export * from './dataPolicies.service';
import { DataPoliciesService } from './dataPolicies.service';
export * from './database.service';
import { DatabaseService } from './database.service';
export * from './descendants.service';
import { DescendantsService } from './descendants.service';
export * from './eAP.service';
import { EAPService } from './eAP.service';
export * from './folder.service';
import { FolderService } from './folder.service';
export * from './label.service';
import { LabelService } from './label.service';
export * from './like.service';
import { LikeService } from './like.service';
export * from './operation.service';
import { OperationService } from './operation.service';
export * from './page.service';
import { PageService } from './page.service';
export * from './redactions.service';
import { RedactionsService } from './redactions.service';
export * from './smartLink.service';
import { SmartLinkService } from './smartLink.service';
export * from './space.service';
import { SpaceService } from './space.service';
export * from './spacePermissions.service';
import { SpacePermissionsService } from './spacePermissions.service';
export * from './spaceProperties.service';
import { SpacePropertiesService } from './spaceProperties.service';
export * from './spaceRoles.service';
import { SpaceRolesService } from './spaceRoles.service';
export * from './task.service';
import { TaskService } from './task.service';
export * from './user.service';
import { UserService } from './user.service';
export * from './version.service';
import { VersionService } from './version.service';
export * from './whiteboard.service';
import { WhiteboardService } from './whiteboard.service';
export const APIS = [AdminKeyService, AncestorsService, AttachmentService, BlogPostService, ChildrenService, ClassificationLevelService, CommentService, ContentService, ContentPropertiesService, CustomContentService, DataPoliciesService, DatabaseService, DescendantsService, EAPService, FolderService, LabelService, LikeService, OperationService, PageService, RedactionsService, SmartLinkService, SpaceService, SpacePermissionsService, SpacePropertiesService, SpaceRolesService, TaskService, UserService, VersionService, WhiteboardService];
