/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Injectable, Optional } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';
import { Observable, from, of, switchMap } from 'rxjs';
import { CreateSpace201Response } from '../model/createSpace201Response';
import { CreateSpaceRequest } from '../model/createSpaceRequest';
import { GetSpaceRolesById200Response } from '../model/getSpaceRolesById200Response';
import { MultiEntityResultSpacePermission } from '../model/multiEntityResultSpacePermission';
import { MultiEntityResultSpaceRole } from '../model/multiEntityResultSpaceRole';
import { MultiEntityResultSpaceRoleAssignment } from '../model/multiEntityResultSpaceRoleAssignment';
import { PrincipalType } from '../model/principalType';
import { SetSpaceRoleAssignmentsRequest } from '../model/setSpaceRoleAssignmentsRequest';
import { Configuration } from '../configuration';
import { COLLECTION_FORMATS } from '../variables';


@Injectable()
export class EAPService {

    protected basePath = 'https://no-default/wiki/api/v2';
    public defaultHeaders: Record<string,string> = {};
    public configuration = new Configuration();
    protected httpClient: HttpService;

    constructor(httpClient: HttpService, @Optional() configuration: Configuration) {
        this.configuration = configuration || this.configuration;
        this.basePath = configuration?.basePath || this.basePath;
        this.httpClient = configuration?.httpClient || httpClient;
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        return consumes.includes(form);
    }

    /**
     * Create space
     * Creates a Space as specified in the payload.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to create spaces.
     * @param createSpaceRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param {*} [createSpaceOpts.config] Override http request option.
     */
    public createSpace(createSpaceRequest: CreateSpaceRequest, createSpaceOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<CreateSpace201Response>>;
    public createSpace(createSpaceRequest: CreateSpaceRequest, createSpaceOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        if (createSpaceRequest === null || createSpaceRequest === undefined) {
            throw new Error('Required parameter createSpaceRequest was null or undefined when calling createSpace.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (basicAuth) required
        if (this.configuration.username || this.configuration.password) {
            headers['Authorization'] = 'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
        }

        // authentication (oAuthDefinitions) required
        if (this.configuration.accessToken) {
            accessTokenObservable = typeof this.configuration.accessToken === 'function'
                ? from(Promise.resolve(this.configuration.accessToken()))
                : from(Promise.resolve(this.configuration.accessToken))
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<CreateSpace201Response>(`${this.basePath}/spaces`,
                    createSpaceRequest,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...createSpaceOpts?.config,
                        headers: {...headers, ...createSpaceOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Get available space permissions
     * Retrieves the available space permissions.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to access the Confluence site.
     * @param cursor Used for pagination, this opaque cursor will be returned in the &#x60;next&#x60; URL in the &#x60;Link&#x60; response header. Use the relative URL in the &#x60;Link&#x60; header to retrieve the &#x60;next&#x60; set of results.
     * @param limit Maximum number of space permissions to return. If more results exist, use the &#x60;Link&#x60; response header to retrieve a relative URL that will return the next set of results.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param {*} [getAvailableSpacePermissionsOpts.config] Override http request option.
     */
    public getAvailableSpacePermissions(cursor?: string, limit?: number, getAvailableSpacePermissionsOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<MultiEntityResultSpacePermission>>;
    public getAvailableSpacePermissions(cursor?: string, limit?: number, getAvailableSpacePermissionsOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        let queryParameters = new URLSearchParams();
        if (cursor !== undefined && cursor !== null) {
            queryParameters.append('cursor', <any>cursor);
        }
        if (limit !== undefined && limit !== null) {
            queryParameters.append('limit', <any>limit);
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (basicAuth) required
        if (this.configuration.username || this.configuration.password) {
            headers['Authorization'] = 'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
        }

        // authentication (oAuthDefinitions) required
        if (this.configuration.accessToken) {
            accessTokenObservable = typeof this.configuration.accessToken === 'function'
                ? from(Promise.resolve(this.configuration.accessToken()))
                : from(Promise.resolve(this.configuration.accessToken))
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<MultiEntityResultSpacePermission>(`${this.basePath}/space-permissions`,
                    {
                        params: queryParameters,
                        withCredentials: this.configuration.withCredentials,
                        ...getAvailableSpacePermissionsOpts?.config,
                        headers: {...headers, ...getAvailableSpacePermissionsOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Get available space roles
     * Retrieves the available space roles.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to access the Confluence site; if requesting a certain space\&#39;s roles, permission to view the space.
     * @param spaceId The space ID for which to filter available space roles; if empty, return all available space roles for the tenant.
     * @param roleType The space role type to filter results by.
     * @param principalId The principal ID to filter results by. If specified, a principal-type must also be specified. Paired with a &#x60;principal-type&#x60; of &#x60;ACCESS_CLASS&#x60;, valid values include [&#x60;anonymous-users&#x60;, &#x60;jsm-project-admins&#x60;, &#x60;authenticated-users&#x60;, &#x60;all-licensed-users&#x60;, &#x60;all-product-admins&#x60;]
     * @param principalType The principal type to filter results by. If specified, a principal-id must also be specified.
     * @param cursor Used for pagination, this opaque cursor will be returned in the &#x60;next&#x60; URL in the &#x60;Link&#x60; response header. Use the relative URL in the &#x60;Link&#x60; header to retrieve the &#x60;next&#x60; set of results.
     * @param limit Maximum number of space roles to return. If more results exist, use the &#x60;Link&#x60; response header to retrieve a relative URL that will return the next set of results.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param {*} [getAvailableSpaceRolesOpts.config] Override http request option.
     */
    public getAvailableSpaceRoles(spaceId?: string, roleType?: string, principalId?: string, principalType?: PrincipalType, cursor?: string, limit?: number, getAvailableSpaceRolesOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<MultiEntityResultSpaceRole>>;
    public getAvailableSpaceRoles(spaceId?: string, roleType?: string, principalId?: string, principalType?: PrincipalType, cursor?: string, limit?: number, getAvailableSpaceRolesOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        let queryParameters = new URLSearchParams();
        if (spaceId !== undefined && spaceId !== null) {
            queryParameters.append('space-id', <any>spaceId);
        }
        if (roleType !== undefined && roleType !== null) {
            queryParameters.append('role-type', <any>roleType);
        }
        if (principalId !== undefined && principalId !== null) {
            queryParameters.append('principal-id', <any>principalId);
        }
        if (principalType !== undefined && principalType !== null) {
            queryParameters.append('principal-type', <any>principalType);
        }
        if (cursor !== undefined && cursor !== null) {
            queryParameters.append('cursor', <any>cursor);
        }
        if (limit !== undefined && limit !== null) {
            queryParameters.append('limit', <any>limit);
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (basicAuth) required
        if (this.configuration.username || this.configuration.password) {
            headers['Authorization'] = 'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
        }

        // authentication (oAuthDefinitions) required
        if (this.configuration.accessToken) {
            accessTokenObservable = typeof this.configuration.accessToken === 'function'
                ? from(Promise.resolve(this.configuration.accessToken()))
                : from(Promise.resolve(this.configuration.accessToken))
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<MultiEntityResultSpaceRole>(`${this.basePath}/space-roles`,
                    {
                        params: queryParameters,
                        withCredentials: this.configuration.withCredentials,
                        ...getAvailableSpaceRolesOpts?.config,
                        headers: {...headers, ...getAvailableSpaceRolesOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Get space role assignments
     * Retrieves the space role assignments.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to view the space.
     * @param id The ID of the space for which to retrieve assignments.
     * @param roleId Filters the returned role assignments to the provided role ID.
     * @param roleType Filters the returned role assignments to the provided role type.
     * @param principalId Filters the returned role assignments to the provided principal id. If specified, a principal-type must also be specified. Paired with a &#x60;principal-type&#x60; of &#x60;ACCESS_CLASS&#x60;, valid values include [&#x60;anonymous-users&#x60;, &#x60;jsm-project-admins&#x60;, &#x60;authenticated-users&#x60;, &#x60;all-licensed-users&#x60;, &#x60;all-product-admins&#x60;]
     * @param principalType Filters the returned role assignments to the provided principal type. If specified, a principal-id must also be specified.
     * @param cursor Used for pagination, this opaque cursor will be returned in the &#x60;next&#x60; URL in the &#x60;Link&#x60; response header. Use the relative URL in the &#x60;Link&#x60; header to retrieve the &#x60;next&#x60; set of results.
     * @param limit Maximum number of space roles to return. If more results exist, use the &#x60;Link&#x60; response header to retrieve a relative URL that will return the next set of results.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param {*} [getSpaceRoleAssignmentsOpts.config] Override http request option.
     */
    public getSpaceRoleAssignments(id: number, roleId?: string, roleType?: string, principalId?: string, principalType?: PrincipalType, cursor?: string, limit?: number, getSpaceRoleAssignmentsOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<MultiEntityResultSpaceRoleAssignment>>;
    public getSpaceRoleAssignments(id: number, roleId?: string, roleType?: string, principalId?: string, principalType?: PrincipalType, cursor?: string, limit?: number, getSpaceRoleAssignmentsOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getSpaceRoleAssignments.');
        }

        let queryParameters = new URLSearchParams();
        if (roleId !== undefined && roleId !== null) {
            queryParameters.append('role-id', <any>roleId);
        }
        if (roleType !== undefined && roleType !== null) {
            queryParameters.append('role-type', <any>roleType);
        }
        if (principalId !== undefined && principalId !== null) {
            queryParameters.append('principal-id', <any>principalId);
        }
        if (principalType !== undefined && principalType !== null) {
            queryParameters.append('principal-type', <any>principalType);
        }
        if (cursor !== undefined && cursor !== null) {
            queryParameters.append('cursor', <any>cursor);
        }
        if (limit !== undefined && limit !== null) {
            queryParameters.append('limit', <any>limit);
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (basicAuth) required
        if (this.configuration.username || this.configuration.password) {
            headers['Authorization'] = 'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
        }

        // authentication (oAuthDefinitions) required
        if (this.configuration.accessToken) {
            accessTokenObservable = typeof this.configuration.accessToken === 'function'
                ? from(Promise.resolve(this.configuration.accessToken()))
                : from(Promise.resolve(this.configuration.accessToken))
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<MultiEntityResultSpaceRoleAssignment>(`${this.basePath}/spaces/${encodeURIComponent(String(id))}/role-assignments`,
                    {
                        params: queryParameters,
                        withCredentials: this.configuration.withCredentials,
                        ...getSpaceRoleAssignmentsOpts?.config,
                        headers: {...headers, ...getSpaceRoleAssignmentsOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Get space role by ID
     * Retrieves the space role by ID.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to access the Confluence site.
     * @param id The ID of the space role to retrieve.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param {*} [getSpaceRolesByIdOpts.config] Override http request option.
     */
    public getSpaceRolesById(id: number, getSpaceRolesByIdOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<GetSpaceRolesById200Response>>;
    public getSpaceRolesById(id: number, getSpaceRolesByIdOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getSpaceRolesById.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (basicAuth) required
        if (this.configuration.username || this.configuration.password) {
            headers['Authorization'] = 'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
        }

        // authentication (oAuthDefinitions) required
        if (this.configuration.accessToken) {
            accessTokenObservable = typeof this.configuration.accessToken === 'function'
                ? from(Promise.resolve(this.configuration.accessToken()))
                : from(Promise.resolve(this.configuration.accessToken))
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<GetSpaceRolesById200Response>(`${this.basePath}/space-roles/${encodeURIComponent(String(id))}`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...getSpaceRolesByIdOpts?.config,
                        headers: {...headers, ...getSpaceRolesByIdOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Set space role assignments
     * Sets space role assignments as specified in the payload.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to manage roles in the space.
     * @param id The ID of the space for which to retrieve assignments.
     * @param setSpaceRoleAssignmentsRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param {*} [setSpaceRoleAssignmentsOpts.config] Override http request option.
     */
    public setSpaceRoleAssignments(id: number, setSpaceRoleAssignmentsRequest: SetSpaceRoleAssignmentsRequest, setSpaceRoleAssignmentsOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<MultiEntityResultSpaceRoleAssignment>>;
    public setSpaceRoleAssignments(id: number, setSpaceRoleAssignmentsRequest: SetSpaceRoleAssignmentsRequest, setSpaceRoleAssignmentsOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling setSpaceRoleAssignments.');
        }

        if (setSpaceRoleAssignmentsRequest === null || setSpaceRoleAssignmentsRequest === undefined) {
            throw new Error('Required parameter setSpaceRoleAssignmentsRequest was null or undefined when calling setSpaceRoleAssignments.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (basicAuth) required
        if (this.configuration.username || this.configuration.password) {
            headers['Authorization'] = 'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password);
        }

        // authentication (oAuthDefinitions) required
        if (this.configuration.accessToken) {
            accessTokenObservable = typeof this.configuration.accessToken === 'function'
                ? from(Promise.resolve(this.configuration.accessToken()))
                : from(Promise.resolve(this.configuration.accessToken))
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<MultiEntityResultSpaceRoleAssignment>(`${this.basePath}/spaces/${encodeURIComponent(String(id))}/role-assignments`,
                    setSpaceRoleAssignmentsRequest,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...setSpaceRoleAssignmentsOpts?.config,
                        headers: {...headers, ...setSpaceRoleAssignmentsOpts?.config?.headers},
                    }
                );
            })
        );
    }
}
